apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - servicemonitors/app-servicemonitor.yaml
  - servicemonitors/ingress-servicemonitor.yaml
  - prometheusrules/rollouts-alerts.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - grafana-dashboards/argo-rollouts.json
      - grafana-dashboards/ingress-nginx.json
      - grafana-dashboards/app-slo.json