apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - rollout.yaml
  - analysis/prometheus-templates.yaml
  - analysis/synthetic-job.yaml
  - monitoring/servicemonitor.yaml